# Generated by Django 4.2.7 on 2025-11-11 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Short biography (max 500 characters)', max_length=500)),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture (recommended: square image, 1MB max)', null=True, upload_to='profiles/%Y/%m/%d/')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=15)),
                ('is_seller', models.BooleanField(default=False, help_text='Is this user a seller?')),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('suspended', 'Suspended')], default='unverified', help_text='Seller account verification status', max_length=20)),
                ('total_sales', models.IntegerField(default=0, help_text='Total number of items sold')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from buyers (0.0 to 5.0)', max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'indexes': [models.Index(fields=['is_seller', '-average_rating'], name='users_userp_is_sell_d4310f_idx'), models.Index(fields=['verification_status'], name='users_userp_verific_48d224_idx')],
            },
        ),
    ]
