# Generated by Django 4.2.7 on 2025-11-19 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon name (e.g., 'fa-utensils')", max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Item title', max_length=200)),
                ('description', models.TextField(help_text='Detailed item description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Item price', max_digits=10)),
                ('condition', models.CharField(choices=[('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('needs_repair', 'Needs Repair')], help_text='Item condition', max_length=20)),
                ('brand', models.CharField(blank=True, help_text='Brand/manufacturer name', max_length=100)),
                ('material', models.CharField(blank=True, help_text='Primary material', max_length=100)),
                ('location', models.CharField(help_text='Pickup/delivery location', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Is item currently available for sale?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Item category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='marketplace.category')),
                ('seller', models.ForeignKey(help_text='Item seller', on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Item image', upload_to='listings/%Y/%m/%d/')),
                ('is_primary', models.BooleanField(default=False, help_text='Use as primary display image?')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(help_text='Associated item', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.item')),
            ],
            options={
                'verbose_name': 'Item Image',
                'verbose_name_plural': 'Item Images',
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['seller', '-created_at'], name='marketplace_seller__c14147_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category', 'is_active'], name='marketplace_categor_34dd1b_idx'),
        ),
    ]
