# Generated by Django 4.2.7 on 2025-11-20 09:48

from django.db import migrations


def seed_categories(apps, schema_editor):
    """Seed default kitchen ware categories"""
    Category = apps.get_model('marketplace', 'Category')
    
    categories = [
        {
            "name": "Cutlery",
            "description": "Knives, forks, spoons, and other utensils for eating",
            "icon": "🔪",
        },
        {
            "name": "Cookware",
            "description": "Pots, pans, skillets, and other cooking vessels",
            "icon": "🍳",
        },
        {
            "name": "Bakeware",
            "description": "Baking pans, cake tins, baking sheets, and pastry tools",
            "icon": "🍰",
        },
        {
            "name": "Smallwares",
            "description": "Whisks, spatulas, measuring cups, and hand tools",
            "icon": "🥄",
        },
        {
            "name": "Glassware & Mugs",
            "description": "Glasses, mugs, cups, and drinkware",
            "icon": "☕",
        },
        {
            "name": "Storage & Organization",
            "description": "Containers, canisters, organizers, and storage solutions",
            "icon": "📦",
        },
        {
            "name": "Small Appliances",
            "description": "Blenders, toasters, coffee makers, and countertop appliances",
            "icon": "⚡",
        },
        {
            "name": "Dinnerware",
            "description": "Plates, bowls, dishes, and tableware",
            "icon": "🍽️",
        },
        {
            "name": "Serving & Entertaining",
            "description": "Serving platters, utensils, and entertaining accessories",
            "icon": "🎉",
        },
        {
            "name": "Other",
            "description": "Miscellaneous kitchen items",
            "icon": "🏠",
        },
    ]
    
    for category_data in categories:
        Category.objects.get_or_create(
            name=category_data["name"],
            defaults={
                "description": category_data["description"],
                "icon": category_data["icon"],
            },
        )


def reverse_categories(apps, schema_editor):
    """Remove seeded categories (optional)"""
    Category = apps.get_model('marketplace', 'Category')
    Category.objects.filter(
        name__in=[
            "Cutlery",
            "Cookware",
            "Bakeware",
            "Smallwares",
            "Glassware & Mugs",
            "Storage & Organization",
            "Small Appliances",
            "Dinnerware",
            "Serving & Entertaining",
            "Other",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_categories, reverse_categories),
    ]
